#!──────────────────────────────────────────────────────────────────────────────────────────────────
#!		THIS FILE WAS CREATED BY SK_AUTORELOAD (SKAR) THE HELPER FOR A BETTER WORKFLOW
#!──────────────────────────────────────────────────────────────────────────────────────────────────

options:
	pre: "-"
	
discord command pay <member> <integer>:
	prefixes: {@pre}
	trigger:
		save all coins of event-member to {_coins}
		if {_coins} - arg-2 < 0:
			make embed:
				set title of embed to " "
				set description of embed to "**Pay:** %discord name of event-member% --> %discord name of arg-1% <:icons8papermoney100:889210789385363576>%nl%```❌  |  You don't have that much coins💰```"
				footertext
			reply with last embed
			
		else:
			give arg-2 to coins of arg-1
			remove arg-2 from coins of event-member
			make embed:
				set title of embed to " "
				set description of embed to "**Pay:** %discord name of event-member% --> %discord name of arg-1% <:icons8papermoney100:889210789385363576>%nl%```✅  |  You payed %arg-2%💰 to %arg-1%```"
				footertext
			reply with last embed
			append "<span class=""pb-1 pt-1""><span class=""bg-blue-500 pl-1 pr-1 pb-1 rounded-b rounded-t"">%arg-2%💰</span> <span><i class=""fa-solid fa-angles-right pl-2 pr-2""></i></span> <span class=""bg-red-500 pl-1 pr-1 pb-1 rounded-b rounded-t"">%discord name of event-member%</span> <span><i class=""fa-solid fa-arrow-right-arrow-left pl-2 pr-2""></i></span> <span class=""bg-green-500 pl-1 pr-1 pb-1 rounded-b rounded-t"">%discord name of arg-1%</span></span>" to file path "/home/pi/minecraft/buddy_bot/plugins/Skript/scripts/data_boddy_website/transactions.txt"
			